CREATE ROLE doonce_app LOGIN PASSWORD 'doonce-app-dev-password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION;
GRANT CONNECT ON DATABASE doonce TO doonce_app;
GRANT USAGE ON SCHEMA public TO doonce_app;
ALTER DEFAULT PRIVILEGES FOR ROLE doonce IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO doonce_app;
